// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"Monitoring-Opportunities/src/api"
	"Monitoring-Opportunities/src/api/controller"
	"Monitoring-Opportunities/src/config"
	"Monitoring-Opportunities/src/database"
	"Monitoring-Opportunities/src/repository"
	"Monitoring-Opportunities/src/services"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	userService := service.NewUserService()
	userController := handler.NewUserController(userService)
	mongoDatabase, err := database.NewMongoDatabase(cfg)
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductRepository(mongoDatabase)
	productService := service.NewProductService(productRepository)
	productController := handler.NewProductController(productService)
	serverHTTP := http.NewServerHTTP(userController, productController)
	return serverHTTP, nil
}
